# SPDX-FileCopyrightText: 2026 EchoVerse contributors
# SPDX-License-Identifier: GPL-3.0-only

services:
  - type: web
    name: echoverse-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
