# SPDX-FileCopyrightText: 2026 EchoVerse contributors
# SPDX-License-Identifier: GPL-3.0-only

version = 1

[[annotations]]
path = "LICENSE"
SPDX-FileCopyrightText = "2007 Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "VERSION"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.json"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "DOCS/**"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ".github/workflows/**"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.png"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.jpg"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.jpeg"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.gif"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.webp"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.ico"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.wav"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.mp3"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.ts"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.tsx"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.cjs"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.css"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.html"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/*.ps1"
SPDX-FileCopyrightText = "2026 EchoVerse contributors"
SPDX-License-Identifier = "GPL-3.0-only"
